apiVersion: v1
kind: Service
metadata:
  name: sv-cloud-app
spec:
  type: NodePort
  selector:
    app: cloud-app
  ports:
  - name: orion
    protocol: TCP
    port: 1026
    targetPort: 1026
  - name: freeboard
    protocol: TCP
    port: 80
    targetPort: 80
  