apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgcap-deployment
spec:
  selector:
    matchLabels:
      app: imgcap
  replicas: 1
  template:
    metadata:
      labels:
        app: imgcap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodes }}
      containers:
      - name:  {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        # - name: FRAME_INTERVAL
        #   value: "5"
        - name: RES_URL
          value: {{ .Values.stream_url }}
        # - name: beam_size
        #   value: "1"
        # - name: max_caption_length
        #   value: "20"

        # https://blog.csdn.net/weixin_36171533/article/details/82771934
        # Handle "Deployment does not have minimum availability."
        resources:
          requests:
            cpu: "2000m"         #cpu最低2000微核，既2个核
            memory: "2000Mi"   #内存最低是9000M
          limits:
            cpu: "4000m"     #cpu最大是8核
            memory: "3000Mi"   #内存最低是12000M
            # nvidia.com/gpu: 1 # requesting 1 GPU


      - name: result-publisher
        image: orangelabschina/result_publisher_arm64
        env:
        - name: TASKID
          value: {{ .Values.task_id }}
        - name: ORION_HOST_PORT
          value: {{ .Values.orion_host_port }}
      - name: message-queue
        image: arm64v8/redis
        ports:
        - containerPort: 6379
