apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgcap-deployment
spec:
  selector:
    matchLabels:
      app: imgcap
  replicas: 1
  template:
    metadata:
      labels:
        app: imgcap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodes }}
      containers:
      - name:  {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: FRAME_INTERVAL
          value: {{ .Values.frame_interval }}
        - name: RES_URL
          value: {{ .Values.stream_url }}
        - name: beam_size
          value: {{ .Values.beam_size }}
        - name: max_caption_length
          value: {{ .Values.max_caption_length }}

      - name: result-publisher
        image: orangelabschina/result_publisher
        env:
        - name: TASKID
          value: {{ .Values.task_id }}
        - name: ORION_HOST_PORT
          value: {{ .Values.orion_host_port }}
      - name: message-queue
        image: redis
        ports:
        - containerPort: 6379
