
mos_image: "mysql"
mos_imageTag: "latest"

mongo_image: "mongo"
mongo_imageTag: "latest"

iotagent_image: "telefonicaiot/iotagent-ul"
iotagent_imageTag: "latest"

# imagePullPolicy: IfNotPresent

nodeSelector: {"worker1"}

# livenessProbe:
#   initialDelaySeconds: 30
#   periodSeconds: 10
#   timeoutSeconds: 5
#   successThreshold: 1
#   failureThreshold: 3

# readinessProbe:
#   initialDelaySeconds: 5
#   periodSeconds: 10
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 3


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
# resources:
#   requests:
#     memory: 256Mi
#     cpu: 100m

# Custom mysql configuration files used to override default mysql settings
configurationFiles:
#  mysql.cnf: |-
#    [mysqld]
#    skip-name-resolve


## Configure the service
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  ## Specify a service type
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  type: ClusterIP
  port: 3306
  # nodePort: 32000
