apiVersion: v1
kind: Service
metadata:
  name: video-stream-app
spec:
  type: NodePort
  selector:
    app: objectdetect
  ports:
  - name: objectdetect-video
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30080
