apiVersion: apps/v1
kind: Deployment
metadata:
  name: penetration-deployment
spec:
  selector:
    matchLabels:
      app: penetration-app
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: penetration-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodes }}
      containers:
      - name: penetration-server
        image: orangelabschina/penetration-arm64
        ports:
        - containerPort: 1038