apiVersion: v1
kind: Service
metadata:
  name: sv-penetration-app
spec:
  type: NodePort
  selector:
    app: penetration-app
  ports:
  - name: app
    protocol: TCP
    port: 1038
    targetPort: 1038
  