apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsi-agent-deployment
spec:
  selector:
    matchLabels:
      app: ngsi-agent-app
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ngsi-agent-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodes }}
      containers:
      - name: ngsi-agent
        image: orangelabschina/ngsi-agent
        ports:
        - containerPort: 1718
        volumeMounts:
          - mountPath: /ngsi-agent/config/rules.json
            subPath: rules.json
            name: rules
        env:
        - name: PENETRATION_SERVER
          value: {{ .Values.penetration_server }}
        - name: NGSI_SERVER
          value: {{ .Values.ngsi_server }}
        - name: AGENT_SELF_URL
          value: {{ .Values.ngsi_agent_server }}
      volumes:
        - name: rules
          configMap:
            name: ngsi-agent-rules
